### ISSUE TITLE
私有云也可以部署吗？

### ISSUE THREAD

**Issue by windghoul** [hbstarjason/spinnaker-auto-install#1]
私有云有没有不使用workflow 的方式进行部署？

**Comment by hbstarjason** [comment]
私有云当然可以部署，但是，必须得科学富强。

**Comment by windghoul** [comment]
也就是说，私有云没法用这个项目进行无梯子安装？

**Comment by hbstarjason** [comment]
不太明白你说的私有云指的是什么，这个项目是自动将spinnaker安装到你的k8s集群上。
条件就是，你的k8s集群需要联网并能够下载github上的spinnaker镜像，并且外部能通过kubectl连接上你的k8s集群。
如果不用这个项目，你的k8s集群还另外必须科学富强才能安装上。

**Comment by windghoul** [comment]
我说的私有云是指，在内网环境外无法访问的集群，谢谢
